[2023-12-14T14:14:07.819+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:14:06.892243+00:00/task_id=ETL permission to 509
[2023-12-14T14:14:07.820+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:14:06.892243+00:00/task_id=ETL permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:14:06.892243+00:00/task_id=ETL'
[2023-12-14T14:14:07.846+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:14:06.892243+00:00/task_id=ETL permission to 509
[2023-12-14T14:14:07.847+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:14:06.892243+00:00/task_id=ETL permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:14:06.892243+00:00/task_id=ETL'
[2023-12-14T14:14:07.881+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.ETL manual__2023-12-14T14:14:06.892243+00:00 [queued]>
[2023-12-14T14:14:07.892+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.ETL manual__2023-12-14T14:14:06.892243+00:00 [queued]>
[2023-12-14T14:14:07.893+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-14T14:14:07.908+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): ETL> on 2023-12-14 14:14:06.892243+00:00
[2023-12-14T14:14:07.914+0000] {standard_task_runner.py:57} INFO - Started process 2395 to run task
[2023-12-14T14:14:07.917+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'ETL', 'manual__2023-12-14T14:14:06.892243+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmp7tm3ut72']
[2023-12-14T14:14:07.919+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask ETL
[2023-12-14T14:14:07.968+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:14:06.892243+00:00/task_id=ETL permission to 509
[2023-12-14T14:14:07.969+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:14:06.892243+00:00/task_id=ETL permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:14:06.892243+00:00/task_id=ETL'
[2023-12-14T14:14:07.971+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.ETL manual__2023-12-14T14:14:06.892243+00:00 [running]> on host d739bc9bef06
[2023-12-14T14:14:08.044+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='ETL' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T14:14:06.892243+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-14T14:14:06.892243+00:00'
[2023-12-14T14:14:08.046+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airQuality.py", line 28, in ETL_airQuality
    response = requests.get(url=url, headers=headers)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 489, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'
[2023-12-14T14:14:08.059+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality, task_id=ETL, execution_date=20231214T141406, start_date=20231214T141407, end_date=20231214T141408
[2023-12-14T14:14:08.072+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task ETL ('str' object has no attribute 'items'; 2395)
[2023-12-14T14:14:08.090+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-14T14:14:08.112+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
