[2023-12-17T05:13:26.019+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:13:19.348806+00:00/task_id=Create_Table permission to 509
[2023-12-17T05:13:26.022+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:13:19.348806+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:13:19.348806+00:00/task_id=Create_Table'
[2023-12-17T05:13:26.053+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:13:19.348806+00:00/task_id=Create_Table permission to 509
[2023-12-17T05:13:26.054+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:13:19.348806+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:13:19.348806+00:00/task_id=Create_Table'
[2023-12-17T05:13:26.089+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.Create_Table manual__2023-12-17T05:13:19.348806+00:00 [queued]>
[2023-12-17T05:13:26.100+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.Create_Table manual__2023-12-17T05:13:19.348806+00:00 [queued]>
[2023-12-17T05:13:26.101+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-17T05:13:26.119+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Create_Table> on 2023-12-17 05:13:19.348806+00:00
[2023-12-17T05:13:26.127+0000] {standard_task_runner.py:57} INFO - Started process 1012 to run task
[2023-12-17T05:13:26.133+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'Create_Table', 'manual__2023-12-17T05:13:19.348806+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmpmavcd3ew']
[2023-12-17T05:13:26.135+0000] {standard_task_runner.py:85} INFO - Job 231: Subtask Create_Table
[2023-12-17T05:13:26.199+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:13:19.348806+00:00/task_id=Create_Table permission to 509
[2023-12-17T05:13:26.200+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:13:19.348806+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:13:19.348806+00:00/task_id=Create_Table'
[2023-12-17T05:13:26.202+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.Create_Table manual__2023-12-17T05:13:19.348806+00:00 [running]> on host 1a58977f5573
[2023-12-17T05:13:26.310+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='Create_Table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-17T05:13:19.348806+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-17T05:13:19.348806+00:00'
[2023-12-17T05:13:26.312+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airQuality.py", line 137, in createTableSQL
    nameOfTABLE = kwargs['tableName']
KeyError: 'tableName'
[2023-12-17T05:13:26.325+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality, task_id=Create_Table, execution_date=20231217T051319, start_date=20231217T051326, end_date=20231217T051326
[2023-12-17T05:13:26.340+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 231 for task Create_Table ('tableName'; 1012)
[2023-12-17T05:13:26.385+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-17T05:13:26.433+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
