[2023-12-14T14:48:45.313+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:43:42.679465+00:00/task_id=ETL permission to 509
[2023-12-14T14:48:45.314+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:43:42.679465+00:00/task_id=ETL permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:43:42.679465+00:00/task_id=ETL'
[2023-12-14T14:48:45.350+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:43:42.679465+00:00/task_id=ETL permission to 509
[2023-12-14T14:48:45.351+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:43:42.679465+00:00/task_id=ETL permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:43:42.679465+00:00/task_id=ETL'
[2023-12-14T14:48:45.392+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.ETL manual__2023-12-14T14:43:42.679465+00:00 [queued]>
[2023-12-14T14:48:45.403+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.ETL manual__2023-12-14T14:43:42.679465+00:00 [queued]>
[2023-12-14T14:48:45.404+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-14T14:48:45.427+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): ETL> on 2023-12-14 14:43:42.679465+00:00
[2023-12-14T14:48:45.433+0000] {standard_task_runner.py:57} INFO - Started process 2929 to run task
[2023-12-14T14:48:45.437+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'ETL', 'manual__2023-12-14T14:43:42.679465+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmp4iy14d1k']
[2023-12-14T14:48:45.438+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask ETL
[2023-12-14T14:48:45.496+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:43:42.679465+00:00/task_id=ETL permission to 509
[2023-12-14T14:48:45.497+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:43:42.679465+00:00/task_id=ETL permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-14T14:43:42.679465+00:00/task_id=ETL'
[2023-12-14T14:48:45.500+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.ETL manual__2023-12-14T14:43:42.679465+00:00 [running]> on host d739bc9bef06
[2023-12-14T14:48:45.601+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='ETL' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T14:43:42.679465+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-14T14:43:42.679465+00:00'
[2023-12-14T14:48:45.603+0000] {logging_mixin.py:154} INFO - https://api.openaq.org/v2/locations
[2023-12-14T14:48:45.603+0000] {logging_mixin.py:154} INFO - {
    'X-API-Key':'dba9e79e0e39099dc324deb6128fa3061bf0db64b458f86c8ccfc5a4f923dde9',
    'accept': 'application/json'
}
[2023-12-14T14:48:45.604+0000] {logging_mixin.py:154} INFO - {
    'country':'ID',
    'city':'Jakarta'
}
[2023-12-14T14:48:45.606+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airQuality.py", line 32, in ETL_airQuality
    response = requests.get(url=url, headers=headers, params=kwargs.get('params'))
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 489, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'
[2023-12-14T14:48:45.626+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=air_quality, task_id=ETL, execution_date=20231214T144342, start_date=20231214T144845, end_date=20231214T144845
[2023-12-14T14:48:45.642+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 48 for task ETL ('str' object has no attribute 'items'; 2929)
[2023-12-14T14:48:45.690+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-14T14:48:45.709+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
