[2023-12-13T12:28:02.780+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-13T12:28:00.426872+00:00/task_id=fetchData permission to 509
[2023-12-13T12:28:02.782+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-13T12:28:00.426872+00:00/task_id=fetchData permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-13T12:28:00.426872+00:00/task_id=fetchData'
[2023-12-13T12:28:02.838+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-13T12:28:00.426872+00:00/task_id=fetchData permission to 509
[2023-12-13T12:28:02.839+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-13T12:28:00.426872+00:00/task_id=fetchData permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-13T12:28:00.426872+00:00/task_id=fetchData'
[2023-12-13T12:28:02.903+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.fetchData manual__2023-12-13T12:28:00.426872+00:00 [queued]>
[2023-12-13T12:28:02.915+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.fetchData manual__2023-12-13T12:28:00.426872+00:00 [queued]>
[2023-12-13T12:28:02.916+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-13T12:28:02.934+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): fetchData> on 2023-12-13 12:28:00.426872+00:00
[2023-12-13T12:28:02.940+0000] {standard_task_runner.py:57} INFO - Started process 741 to run task
[2023-12-13T12:28:02.944+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'fetchData', 'manual__2023-12-13T12:28:00.426872+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmpdqubyruh']
[2023-12-13T12:28:02.945+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask fetchData
[2023-12-13T12:28:03.005+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-13T12:28:00.426872+00:00/task_id=fetchData permission to 509
[2023-12-13T12:28:03.006+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-13T12:28:00.426872+00:00/task_id=fetchData permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-13T12:28:00.426872+00:00/task_id=fetchData'
[2023-12-13T12:28:03.008+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.fetchData manual__2023-12-13T12:28:00.426872+00:00 [running]> on host d739bc9bef06
[2023-12-13T12:28:03.095+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='fetchData' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T12:28:00.426872+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-13T12:28:00.426872+00:00'
[2023-12-13T12:28:03.097+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airQuality.py", line 35, in fetchData
    apiResult = ti.xcom_pull(
NameError: name 'ti' is not defined
[2023-12-13T12:28:03.111+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality, task_id=fetchData, execution_date=20231213T122800, start_date=20231213T122802, end_date=20231213T122803
[2023-12-13T12:28:03.128+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task fetchData (name 'ti' is not defined; 741)
[2023-12-13T12:28:03.158+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-13T12:28:03.192+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
