[2023-12-16T12:59:58.854+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-16T12:50:47.142901+00:00/task_id=Insert_Data permission to 509
[2023-12-16T12:59:58.856+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-16T12:50:47.142901+00:00/task_id=Insert_Data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-16T12:50:47.142901+00:00/task_id=Insert_Data'
[2023-12-16T12:59:58.909+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-16T12:50:47.142901+00:00/task_id=Insert_Data permission to 509
[2023-12-16T12:59:58.911+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-16T12:50:47.142901+00:00/task_id=Insert_Data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-16T12:50:47.142901+00:00/task_id=Insert_Data'
[2023-12-16T12:59:58.974+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.Insert_Data manual__2023-12-16T12:50:47.142901+00:00 [queued]>
[2023-12-16T12:59:58.995+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.Insert_Data manual__2023-12-16T12:50:47.142901+00:00 [queued]>
[2023-12-16T12:59:58.996+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-12-16T12:59:59.018+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Insert_Data> on 2023-12-16 12:50:47.142901+00:00
[2023-12-16T12:59:59.023+0000] {standard_task_runner.py:57} INFO - Started process 2271 to run task
[2023-12-16T12:59:59.026+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'Insert_Data', 'manual__2023-12-16T12:50:47.142901+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmpe75qcu2o']
[2023-12-16T12:59:59.028+0000] {standard_task_runner.py:85} INFO - Job 157: Subtask Insert_Data
[2023-12-16T12:59:59.080+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-16T12:50:47.142901+00:00/task_id=Insert_Data permission to 509
[2023-12-16T12:59:59.081+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-16T12:50:47.142901+00:00/task_id=Insert_Data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-16T12:50:47.142901+00:00/task_id=Insert_Data'
[2023-12-16T12:59:59.084+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.Insert_Data manual__2023-12-16T12:50:47.142901+00:00 [running]> on host d739bc9bef06
[2023-12-16T12:59:59.181+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='Insert_Data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T12:50:47.142901+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T12:50:47.142901+00:00'
[2023-12-16T12:59:59.728+0000] {logging_mixin.py:154} INFO - city           object
country        object
unit           object
last_value    float64
lat           float64
lng           float64
dtype: object
[2023-12-16T12:59:59.742+0000] {base.py:73} INFO - Using connection ID 'neonServerDB-Postgres' for task execution.
[2023-12-16T13:00:05.484+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airQuality.py", line 151, in insertValues
    conn.insert_rows(
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'insert_rows'
[2023-12-16T13:00:05.506+0000] {taskinstance.py:211} INFO - Setting task Error_Response to SKIPPED due to dag's `fail_stop` setting.
[2023-12-16T13:00:05.507+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=air_quality, task_id=Insert_Data, execution_date=20231216T125047, start_date=20231216T125958, end_date=20231216T130005
[2023-12-16T13:00:05.542+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 157 for task Insert_Data ('psycopg2.extensions.connection' object has no attribute 'insert_rows'; 2271)
[2023-12-16T13:00:05.556+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T13:00:05.575+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
